qm_method: b3lyp-d3bj
qm_basis: dzvp
bond_steps:
    - -0.3
    - -0.2
    - -0.15
    - -0.1
    - -0.05
    - 0.0
    - 0.05
    - 0.1
    - 0.15
    - 0.2
    - 0.3
angle_steps:
    - -20
    - -15
    - -10
    - -5
    - 0
    - 5
    - 10
    - 15
    - 20
